[publication]
id = "tbtvcn"
name = "Trung Bac Tan Van Chu Nhat"

[target]
type = "gcs"
project = "vie-ocr"
bucket = "vie-doc"
pdf_prefix = "tbtvcn/pdf"
images_prefix = "tbtvcn/images"
ocr_output_prefix = "tbtvcn/ocr"

[source]
type = "local_dir"
path = "../data/tbtvcn/pdf"
# original: http://ndclnh-mytho-usa.org/Trung%20Bac%20Tan%20Van%20Chu%20Nhat.htm

[explode]
# Run `vie-pipeline calibrate tbtvcn --pdf <file>` to determine best params
preserve_crop = true
negate_png = false
preserve_orientation = false
no_text = false
dpi = 300

[ocr]
language_hints = ["vi"]
